<?php
/**
 * Departments & Specializations Section
 * Figma Node: 249:6559 / 212:857
 */
?>
<section class="departments-section" id="departments">
    <div class="container">
        <div class="section-title-wrap">
            <h2 class="h2-title" data-i18n="departments.title">Наши отделения</h2>
        </div>

        <div class="dept-controls">
            <div class="dept-search-wrap">
                <svg class="dept-search-icon" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>
                <input type="text" id="dept-search-input" placeholder="Найти направление, специалиста или услугу..." data-i18n="departments.search_placeholder">
            </div>

            <div class="dept-tabs-bar">
                <button type="button" class="dept-tab-btn active" data-category="all" data-i18n="departments.tab_all">Направления</button>
                <button type="button" class="dept-tab-btn" data-category="specialists">Специалисты</button>
                <button type="button" class="dept-tab-btn" data-category="diagnostics">Диагностика</button>
                <button type="button" class="dept-tab-btn" data-category="tests">Анализы</button>
            </div>
        </div>

        <div class="dept-grid-fignode" id="dept-grid-container">
            <!-- 🩺 1. НАПРАВЛЕНИЯ (DIRECTIONS) -->
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.endocrinology">Эндокринология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name">Остеопатия</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.neurology">Неврология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.orthopedics">Ортопедия и травматология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.podology">Подология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.podiatry">Подиатрия</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.psychology">Психотерапия</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.kinesiology">Кинезиология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name">Гирудотерапия</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode wide-2col" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name">Вертеброневрология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.vertebrology">Вертебрология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.phlebology">Флебология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name">Терапия</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.urology">Урология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.dietetics">Диетология и нутрициология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.epileptology">Эпилептология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.rheumatology">Ревматология</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.homeopathy">Гомеопатия</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode wide-2col" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.manual">Мануальная терапия</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode wide-2col" data-category="directions"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Направление</span><div class="dept-card-name" data-i18n="dept.integrative">Интегративная медицина</div></div></a>

            <!-- 👨‍⚕️ 2. СПЕЦИАЛИСТЫ (SPECIALISTS) -->
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Врач-эндокринолог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Врач-остеопат</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Врач-невролог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Травматолог-ортопед</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Специалист</span><div class="dept-card-name">Подолог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Врач-подиатр</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Психотерапевт</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Специалист</span><div class="dept-card-name">Прикладной кинезиолог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Гирудотерапевт</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode wide-2col" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Вертеброневролог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Вертебролог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Врач-флеболог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Врач-терапевт</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Врач-уролог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Диетолог-нутрициолог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Эпилептолог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Врач-ревматолог</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Врач-гомеопат</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode wide-2col" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Мануальный терапевт</div></div></a>
            <a href="<?php echo esc_url(home_url('/doctors/')); ?>" class="dept-card-fignode wide-2col" data-category="specialists"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Врач</span><div class="dept-card-name">Врач интегративной медицины</div></div></a>

            <!-- 🔬 3. ДИАГНОСТИКА (DIAGNOSTICS) -->
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">УЗИ</span><div class="dept-card-name">УЗИ экспертного класса</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">УЗИ</span><div class="dept-card-name">УЗИ сосудов головы и шеи</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">УЗИ</span><div class="dept-card-name">УЗИ суставов и связок</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Кардио</span><div class="dept-card-name">ЭКГ с расшифровкой</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Кардио</span><div class="dept-card-name">Холтер-мониторирование</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Кардио</span><div class="dept-card-name">СМАД (мониторинг АД)</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Диагностика</span><div class="dept-card-name">Биоимпедансометрия тела</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Ортопедия</span><div class="dept-card-name">Компьютерная плантография</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Дерматология</span><div class="dept-card-name">Цифровая видеодерматоскопия</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode wide-2col" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Check-up</span><div class="dept-card-name">Комплексный Check-up «Здоровье 360°»</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Остеопатия</span><div class="dept-card-name">Остеопатическая диагностика</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Кинезио</span><div class="dept-card-name">Оценка постурального баланса</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode wide-2col" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Check-up</span><div class="dept-card-name">Скрининг гормонального статуса</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode wide-2col" data-category="diagnostics"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Неврология</span><div class="dept-card-name">Нейросонография с допплерографией</div></div></a>

            <!-- 🧪 4. АНАЛИЗЫ (TESTS) -->
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Анализы</span><div class="dept-card-name">Гормональный профиль щитовидной железы</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Анализы</span><div class="dept-card-name">Половой гормональный профиль</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Биохимия</span><div class="dept-card-name">Биохимический анализ крови (28 пок.)</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Базовый</span><div class="dept-card-name">Клинический анализ крови + СОЭ</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Дефициты</span><div class="dept-card-name">Витамины D3, B12, B9 и ферритин</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Интегративная</span><div class="dept-card-name">Детокс-панель и токсичные металлы</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Интегративная</span><div class="dept-card-name">Оксидативный стресс и антиоксиданты</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Кардио</span><div class="dept-card-name">Липидограмма и риски атеросклероза</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Онко</span><div class="dept-card-name">Онкомаркеры базовые и расширенные</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Иммунология</span><div class="dept-card-name">Иммунограмма и маркеры воспаления</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Генетика</span><div class="dept-card-name">Генетический паспорт нутригенетики</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Аллергия</span><div class="dept-card-name">Тест пищевой непереносимости (IgG4)</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Стресс</span><div class="dept-card-name">Суточный кортизол в слюне (ритм стресса)</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode wide-2col" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Микробиота</span><div class="dept-card-name">Анализ микробиоты по Осипову (ХМС)</div></div></a>
            <a href="<?php echo esc_url(home_url('/services/')); ?>" class="dept-card-fignode wide-2col" data-category="tests"><div class="dept-card-ico-fig"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/assets/e9816969a128a37e3a6d1256280e5c8cb21a91e0.svg'); ?>" alt="" style="width:24px;height:24px;"></div><div class="dept-card-text-fig"><span class="dept-card-badge">Комплекс</span><div class="dept-card-name">Комплексный детокс-скрининг организма</div></div></a>
        </div>
    </div>
</section>
